server:
  port: 8080
spring:
  application:
    name: spring-application-webflux
  datasource:
    url: jdbc:h2:mem:hellodb
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jooq:
    sql-dialect: H2
  h2:
    console.enabled: true
